blank_issues_enabled: true
contact_links:
  - name: â“ Ask a Question
    url: https://github.com/vueform/vueform/discussions/categories/questions
    about: Not sure about something? Start a "New discussion" and get an answer
  - name: ğŸ’¡ Feature Idea
    url: https://github.com/vueform/vueform/discussions/categories/ideas
    about: Suggest a feature that will improve Vueform by starting a "New discussion"
  - name: ğŸ“š Learning Guide
    url: https://vueform.com/docs/input-mask
    about: Learning material for Vueform